TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 0.04
  acc_lim_y: 0.04
  acc_lim_theta: 0.25

  max_vel_x: 0.08 #0.05
  min_vel_x: 0.05 #0.009
  max_vel_theta: 0.08
  min_vel_theta: -0.08
  min_in_place_vel_theta: 0.08

  escape_vel: -0.04

  holonomic_robot: false

  # Forward Simulation Parameters
  sim_time: 1.0 #The amount of time to forward-simulate trajectories in seconds (default: 1.0)
  sim_granularity: 0.1 #The step size, in meters, to take between points on a given trajectory (default:0.025)
  angular_sim_granularity: 0.025 #The step size, in radians, to take between angular samples on a given trajectory
  vx_samples: 20 #The number of samples to use when exploring the x velocity space (default: 3)
  vtheta_samples: 40 #The number of samples to use when exploring the theta velocity space (default: 20)
  controller_frequency: 20 #The frequency at which this controller will be called in Hz. Uses searchParam to read the parameter from parent namespaces if not set in the namespace of the controller. For use with move_base, this means that you only need to set its "controller_frequency" parameter and can safely leave this one unset. (default:20.0)
  
  # Goal Tolerance Parameters
  yaw_goal_tolerance: 4.0 #=20deg  #0.15 # = 10 deg
  xy_goal_tolerance: 0.30 
  latch_xy_goal_tolerance: true #If goal tolerance is latched, if the robot ever reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so.

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.5 # How far the robot must travel in meters before oscillation flags are reset


  #Trajectory Scoring Parameters
  meter_scoring: true #Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default.
  path_distance_bias: 0.5
   #WORKING:2 #0.01 #The weighting for how much the controller should stay close to the path it was given, maximal possible value is 5.0
  goal_distance_bias: 5.0 #4.0 #The weighting for how much the controller should attempt to reach its local goal, also controls speed, maximal possible value is 5.0
  occdist_scale: 0.02 #0.0 #The weighting for how much the controller should attempt to avoid obstacles

  dwa: true

#R = 0.0350;
#L = 0.3550;
#gear reduction = 172

#accel t = 0.04261850499055921
#alpha t = 0.2401042534679392
#v t max = 0.06392775748583882
#v t min = 0.008523700998111842
#w t max = 0.3601563802019088
#w t min = 0.04802085069358784
