obstacle_range: 2.5 # maximum range sensor reading that will result in an obstacle being put into costmap
raytrace_range: 3.0 # freespace raytracing range given a sensor reading; distance up to which the robot attempts to clear out space in front of it 
footprint: [[0.3575, 0.0135], [0.3275, 0.157], [0.3115, 0.222],[0.2695, 0.222], [-0.035, 0.199], [-0.0525, 0.157], [-0.0525, -0.157], [-0.035, -0.199], [0.2695, -0.222], [0.3115, -0.222], [0.3275, -0.157], [0.3575, -0.0135]]
inflation_radius: 0.55

#observation_sources: laser_scan_sensor point_cloud_sensor
#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
observation_sources: fm_tof fr_tof fl_tof sr_tof sl_tof bm_tof
fm_tof: {sensor_frame: tof_fm_frame, data_type: Range, topic: tof_fm_link, marking: true, clearing: true}
fr_tof: {sensor_frame: tof_fr_frame, data_type: Range, topic: tof_fr_link, marking: true, clearing: true}
fl_tof: {sensor_frame: tof_fl_frame, data_type: Range, topic: tof_fl_link, marking: true, clearing: true}
sr_tof: {sensor_frame: tof_sr_frame, data_type: Range, topic: tof_sr_link, marking: true, clearing: true}
sl_tof: {sensor_frame: tof_sl_frame, data_type: Range, topic: tof_sl_link, marking: true, clearing: true}
bm_tof: {sensor_frame: tof_bm_frame, data_type: Range, topic: tof_bm_link, marking: true, clearing: true}

#topics: ['/tof_fm', ....])
#    List of Range topics to subscribe to 
#no_readings_timeout (double, default: 0.0)
#    If zero, this parameter has no effect. Otherwise if the layer does not receive sensor data for this amount of time, the layer will warn the user and the layer will be marked as not current. 
#clear_threshold (double, default: .2)
#    Cells with a probability lower than the clear_threshold are marked as free space in the master costmap. 
#mark_threshold (double, default: .8)
#    Cells with a probability higher than the mark_threshold are marked as lethal obstacles in the master costmap. 
#clear_on_max_reading (bool, default: false) 
