#obstacle_range: 2.5 # maximum range sensor reading that will result in an obstacle being put into costmap
footprint: [[0.3575, 0.0135], [0.3275, 0.157], [0.3115, 0.222],[0.2695, 0.222], [-0.035, 0.199], [-0.0525, 0.157], [-0.0525, -0.157], [-0.035, -0.199], [0.2695, -0.222], [0.3115, -0.222], [0.3275, -0.157], [0.3575, -0.0135]]

plugins:
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: range_layer,     type: "range_sensor_layer::RangeSensorLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

range_layer:
  topics: ["fm_tof", "fr_tof", "fl_tof", "sr_tof", "sl_tof", "bm_tof"]
  no_readings_timeout: 0
  clear_threshold: 0.2
  mark_threshold: 0.8
  clear_on_max_reading: false

inflation_layer:
  enabled:             true
  cost_scaling_factor: 10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:    0.02  # max. distance from an obstacle at which costs are incurred for planning paths.
