local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 50.0
  publish_frequency: 50.0
  static_map: false
  rolling_window: true # whether costmap remains centered around robot as the robot moves through the world
  # size of local costmap in [m]
  width: 3.0
  height: 3.0
  resolution: 0.01
  