local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true # whether costmap remains centered around robot as the robot moves through the world
  # size of local costmap in [m]
  width: 3.0
  height: 3.0
  resolution: 0.01    # 0.05 - 0.1

  plugins:
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: range_sensor_layer, type: "range_sensor_layer::RangeSensorLayer"}
    - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
